spring:
  application:
    name: administration
  datasource:
    url: jdbc:postgresql://postgres:5432/${spring.application.name}
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate