-- liquibase formatted sql

-- changeset Admin:1720516905534-1
CREATE TABLE hall
(
    id       UUID         NOT NULL,
    name     VARCHAR(32)  NOT NULL,
    capacity INTEGER      NOT NULL,
    seats    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_hall PRIMARY KEY (id)
);

-- changeset Admin:1720516905534-2
CREATE TABLE movie
(
    id          UUID        NOT NULL,
    title       VARCHAR(32) NOT NULL,
    duration INTERVAL NOT NULL,
    description VARCHAR(512),
    CONSTRAINT pk_movie PRIMARY KEY (id)
);

-- changeset Admin:1720516905534-3
CREATE TABLE place
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    in_row_id INTEGER                                  NOT NULL,
    occupied  BOOLEAN,
    row_id    INTEGER                                  NOT NULL,
    CONSTRAINT pk_place PRIMARY KEY (id)
);

-- changeset Admin:1720516905534-4
CREATE TABLE row
(
    id          INTEGER NOT NULL,
    free_places INTEGER NOT NULL,
    session_id  UUID    NOT NULL,
    CONSTRAINT pk_row PRIMARY KEY (id)
);

-- changeset Admin:1720516905534-5
CREATE TABLE session
(
    id          UUID         NOT NULL,
    movie       VARCHAR(255) NOT NULL,
    hall_id     UUID         NOT NULL,
    start_time  time WITHOUT TIME ZONE NOT NULL,
    end_time    time WITHOUT TIME ZONE NOT NULL,
    price       INTEGER      NOT NULL,
    free_places INTEGER      NOT NULL,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

-- changeset Admin:1720516905534-6
CREATE TABLE "user"
(
    id    UUID        NOT NULL,
    phone VARCHAR(11) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

-- changeset Admin:1720516905534-7
ALTER TABLE "user"
    ADD CONSTRAINT uc_user_phone UNIQUE (phone);

-- changeset Admin:1720516905534-8
ALTER TABLE place
    ADD CONSTRAINT FK_PLACE_ON_ROWID FOREIGN KEY (row_id) REFERENCES row (id);

-- changeset Admin:1720516905534-9
ALTER TABLE row
    ADD CONSTRAINT FK_ROW_ON_SESSION FOREIGN KEY (session_id) REFERENCES session (id);

-- changeset Admin:1720516905534-10
ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_HALL FOREIGN KEY (hall_id) REFERENCES hall (id);

