apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app.kubernetes.io/name: cinema
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cinema
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cinema
    spec:
      restartPolicy: Always
      containers:
        - name: service
          image: localhost:32000/cinema:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 60
          resources:
            limits:
              cpu: "1"
              memory: 800Mi
            requests:
              cpu: 250m
              memory: 800Mi
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-0.postgres:5432/cinema"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cinema
  labels:
    app.kubernetes.io/name: team4
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cinema